In [1]:
from nba_api.stats.endpoints import playercareerstats
# Anthony Davis
career = playercareerstats.PlayerCareerStats(player_id='203076')
career.get_data_frames()[0]

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
ls

Player.ipynb        PlayerCharts.ipynb

In [ ]:
#Lester Hudson
career = playercareerstats.PlayerCareerStats(player_id='201991')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,201991,2009-10,00,1610612738,BOS,25.0,16,0,70.0,7,...,0.833,3,5,8,8,3,2,9,7,22
1,201991,2009-10,00,1610612763,MEM,25.0,9,0,61.0,14,...,0.857,4,6,10,5,5,1,5,5,36
2,201991,2009-10,00,0,TOT,25.0,25,0,131.0,21,...,0.846,7,11,18,13,8,3,14,12,58
3,201991,2010-11,00,1610612764,WAS,26.0,11,0,73.0,6,...,0.500,1,4,5,17,4,1,7,10,18
4,201991,2011-12,00,1610612739,CLE,27.0,13,0,314.0,59,...,0.842,7,39,46,35,14,3,30,26,165
5,201991,2011-12,00,1610612763,MEM,27.0,3,0,20.0,3,...,0.667,0,0,0,1,0,0,2,0,9
6,201991,2011-12,00,0,TOT,27.0,16,0,334.0,62,...,0.829,7,39,46,36,14,3,32,26,174
7,201991,2014-15,00,1610612746,LAC,30.0,5,0,56.0,6,...,0.750,1,7,8,5,6,1,3,4,18

In [ ]:
#Nikola Jokic
career = playercareerstats.PlayerCareerStats(player_id='203999')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,2015-16,00,1610612743,DEN,21.0,80,55,1733.0,307,...,0.811,181,379,560,189,79,50,104,208,796
1,203999,2016-17,00,1610612743,DEN,22.0,73,59,2038.0,494,...,0.825,212,506,718,359,61,55,171,214,1221
2,203999,2017-18,00,1610612743,DEN,23.0,75,73,2443.0,504,...,0.850,195,608,803,458,90,61,210,212,1385
3,203999,2018-19,00,1610612743,DEN,24.0,80,80,2504.0,616,...,0.821,228,637,865,580,108,55,248,228,1604
4,203999,2019-20,00,1610612743,DEN,25.0,73,73,2335.0,565,...,0.817,166,545,711,512,85,44,226,222,1456
5,203999,2020-21,00,1610612743,DEN,26.0,72,72,2488.0,732,...,0.868,205,575,780,599,95,48,222,192,1898
6,203999,2021-22,00,1610612743,DEN,27.0,74,74,2476.0,764,...,0.810,206,813,1019,584,109,63,281,191,2004
7,203999,2022-23,00,1610612743,DEN,28.0,54,54,1818.0,509,...,0.824,123,509,632,541,70,36,192,140,1340

In [ ]:

#Stephen Curry
career = playercareerstats.PlayerCareerStats(player_id='201939')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,201939,2009-10,00,1610612744,GSW,22.0,80,77,2896.0,528,...,0.885,48,308,356,472,152,19,243,252,1399
1,201939,2010-11,00,1610612744,GSW,23.0,74,74,2489.0,505,...,0.934,52,234,286,432,109,20,226,233,1373
2,201939,2011-12,00,1610612744,GSW,24.0,26,23,732.0,145,...,0.809,15,73,88,138,39,8,65,62,383
3,201939,2012-13,00,1610612744,GSW,25.0,78,78,2983.0,626,...,0.900,59,255,314,539,126,12,240,198,1786
4,201939,2013-14,00,1610612744,GSW,26.0,78,78,2846.0,652,...,0.885,46,288,334,666,128,14,294,194,1873
5,201939,2014-15,00,1610612744,GSW,27.0,80,80,2613.0,653,...,0.914,56,285,341,619,163,16,249,158,1900
6,201939,2015-16,00,1610612744,GSW,28.0,79,79,2700.0,805,...,0.908,68,362,430,527,169,15,262,161,2375
7,201939,2016-17,00,1610612744,GSW,29.0,79,79,2639.0,675,...,0.898,61,292,353,524,142,17,239,183,1999
8,201939,2017-18,00,1610612744,GSW,30.0,51,51,1631.0,428,...,0.921,36,225,261,310,80,8,153,114,1346
9,201939,2018-19,00,1610612744,GSW,31.0,69,69,2331.0,632,...,0.916,45,324,369,361,92,25,192,166,1881
10,201939,2019-20,00,1610612744,GSW,32.0,5,5,139.0,33,...,1.000,4,22,26,33,5,2,16,11,104
11,201939,2020-21,00,1610612744,GSW,33.0,63,63,2152.0,658,...,0.916,29,316,345,363,77,8,213,119,2015
12,201939,2021-22,00,1610612744,GSW,34.0,64,64,2211.0,535,...,0.923,34,301,335,404,85,23,206,130,1630
13,201939,2022-23,00,1610612744,GSW,34.0,38,38,1313.0,372,...,0.922,22,219,241,244,37,15,122,82,1119

In [ ]:

#Kevin Durrant
career = playercareerstats.PlayerCareerStats(player_id='201142')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,201142,2007-08,00,1610612760,SEA,19.0,80,80,2768.0,587,...,0.873,70,278,348,192,78,75,232,122,1624
1,201142,2008-09,00,1610612760,OKC,20.0,74,74,2885.0,661,...,0.863,77,405,482,205,96,53,225,134,1871
2,201142,2009-10,00,1610612760,OKC,21.0,82,82,3239.0,794,...,0.900,105,518,623,231,112,84,271,171,2472
3,201142,2010-11,00,1610612760,OKC,22.0,78,78,3038.0,711,...,0.880,57,476,533,214,88,76,218,159,2161
4,201142,2011-12,00,1610612760,OKC,23.0,66,66,2546.0,643,...,0.860,40,487,527,231,88,77,248,133,1850
5,201142,2012-13,00,1610612760,OKC,24.0,81,81,3119.0,731,...,0.905,46,594,640,374,116,105,280,143,2280
6,201142,2013-14,00,1610612760,OKC,25.0,81,81,3122.0,849,...,0.873,58,540,598,445,103,59,285,174,2593
7,201142,2014-15,00,1610612760,OKC,26.0,27,27,913.0,238,...,0.854,16,162,178,110,24,25,74,40,686
8,201142,2015-16,00,1610612760,OKC,27.0,72,72,2578.0,698,...,0.898,45,544,589,361,69,85,250,137,2029
9,201142,2016-17,00,1610612744,GSW,28.0,62,62,2070.0,551,...,0.875,39,474,513,300,66,99,138,117,1555
10,201142,2017-18,00,1610612744,GSW,29.0,68,68,2325.0,630,...,0.889,31,433,464,366,50,119,207,133,1792
11,201142,2018-19,00,1610612744,GSW,30.0,78,78,2702.0,721,...,0.885,33,464,497,457,58,84,225,155,2027
12,201142,2020-21,00,1610612751,BKN,32.0,35,32,1157.0,324,...,0.882,13,234,247,195,25,45,120,70,943
13,201142,2021-22,00,1610612751,BKN,33.0,55,55,2047.0,578,...,0.910,29,378,407,351,48,52,191,113,1643
14,201142,2022-23,00,1610612751,BKN,34.0,39,39,1403.0,410,...,0.934,14,248,262,207,32,57,136,92,1158

In [ ]:

#Lebron James
career = playercareerstats.PlayerCareerStats(player_id='2544')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,...,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,...,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,...,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,...,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,...,0.712,133,459,592,539,138,81,255,165,2250
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,3054.0,789,...,0.780,106,507,613,587,137,93,241,139,2304
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,2966.0,768,...,0.767,71,483,554,651,125,77,261,119,2258
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,3063.0,758,...,0.759,80,510,590,554,124,50,284,163,2111
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,2326.0,621,...,0.771,94,398,492,387,115,50,213,96,1683
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,2877.0,765,...,0.753,97,513,610,551,129,67,226,110,2036
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,2902.0,767,...,0.750,81,452,533,488,121,26,270,126,2089
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,2493.0,624,...,0.710,51,365,416,511,109,49,272,135,1743
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,2709.0,737,...,0.731,111,454,565,514,104,49,249,143,1920
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,2795.0,736,...,0.674,97,542,639,646,92,44,303,134,1954
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,3026.0,857,...,0.731,97,612,709,747,116,71,347,136,2251
15,2544,2018-19,00,1610612747,LAL,34.0,55,55,1937.0,558,...,0.665,57,408,465,454,72,33,197,94,1505
16,2544,2019-20,00,1610612747,LAL,35.0,67,67,2316.0,643,...,0.693,66,459,525,684,78,36,261,118,1698
17,2544,2020-21,00,1610612747,LAL,36.0,45,45,1504.0,422,...,0.698,29,317,346,350,48,25,168,70,1126
18,2544,2021-22,00,1610612747,LAL,37.0,56,56,2084.0,640,...,0.756,63,396,459,349,73,59,196,121,1695
19,2544,2022-23,00,1610612747,LAL,38.0,47,47,1695.0,532,...,0.759,57,339,396,326,44,26,147,79,1388

In [ ]:

#Trae Young
career = playercareerstats.PlayerCareerStats(player_id='1629027')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1629027,2018-19,00,1610612737,ATL,20.0,81,81,2503.0,525,...,0.829,64,237,301,653,72,15,308,140,1549
1,1629027,2019-20,00,1610612737,ATL,21.0,60,60,2120.0,546,...,0.860,32,223,255,560,65,8,289,104,1778
2,1629027,2020-21,00,1610612737,ATL,22.0,63,63,2125.0,487,...,0.886,38,207,245,594,53,12,261,111,1594
3,1629027,2021-22,00,1610612737,ATL,23.0,76,76,2652.0,711,...,0.904,50,234,284,737,72,7,303,128,2155
4,1629027,2022-23,00,1610612737,ATL,24.0,54,54,1907.0,458,...,0.889,39,120,159,550,57,8,221,83,1458

In [ ]:

#Jayson Tatum
career = playercareerstats.PlayerCareerStats(player_id='1628369')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1628369,2017-18,00,1610612738,BOS,20.0,80,80,2443.0,397,...,0.826,50,352,402,128,83,58,114,170,1112
1,1628369,2018-19,00,1610612738,BOS,21.0,79,79,2455.0,466,...,0.855,70,407,477,168,84,57,122,168,1243
2,1628369,2019-20,00,1610612738,BOS,22.0,66,66,2265.0,552,...,0.812,64,396,460,200,93,57,155,136,1547
3,1628369,2020-21,00,1610612738,BOS,23.0,64,64,2290.0,605,...,0.868,50,422,472,276,75,31,171,122,1692
4,1628369,2021-22,00,1610612738,BOS,24.0,76,76,2731.0,708,...,0.853,85,524,609,334,75,49,217,174,2046
5,1628369,2022-23,00,1610612738,BOS,24.0,57,57,2129.0,563,...,0.864,63,435,498,263,59,45,168,122,1734

In [ ]:

#Terry Rozier
career = playercareerstats.PlayerCareerStats(player_id='1626179')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1626179,2015-16,00,1610612738,BOS,22.0,39,0,311.0,29,...,0.800,24,39,63,37,6,1,19,23,72
1,1626179,2016-17,00,1610612738,BOS,23.0,74,0,1263.0,151,...,0.773,40,187,227,131,45,11,47,69,410
2,1626179,2017-18,00,1610612738,BOS,24.0,80,16,2068.0,316,...,0.772,63,313,376,232,80,19,80,123,900
3,1626179,2018-19,00,1610612738,BOS,25.0,79,14,1791.0,258,...,0.785,32,275,307,231,68,21,68,101,708
4,1626179,2019-20,00,1610612766,CHA,26.0,63,63,2165.0,398,...,0.874,50,226,276,259,61,10,141,126,1134
5,1626179,2020-21,00,1610612766,CHA,27.0,69,69,2383.0,510,...,0.817,47,255,302,293,87,26,128,119,1407
6,1626179,2021-22,00,1610612766,CHA,28.0,73,73,2458.0,518,...,0.852,56,259,315,326,93,25,96,119,1408
7,1626179,2022-23,00,1610612766,CHA,28.0,52,52,1851.0,410,...,0.827,47,169,216,250,58,13,107,98,1112

In [ ]:

#DeMar DeRozan
career = playercareerstats.PlayerCareerStats(player_id='201942')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,201942,2009-10,00,1610612761,TOR,20.0,77,65,1664.0,255,...,0.763,66,157,223,53,43,18,62,176,662
1,201942,2010-11,00,1610612761,TOR,21.0,82,82,2851.0,539,...,0.813,75,240,315,148,85,31,144,217,1410
2,201942,2011-12,00,1610612761,TOR,22.0,63,63,2206.0,381,...,0.810,40,171,211,128,48,17,123,162,1054
3,201942,2012-13,00,1610612761,TOR,23.0,82,82,3013.0,548,...,0.831,48,272,320,204,76,24,151,173,1485
4,201942,2013-14,00,1610612761,TOR,24.0,79,79,3017.0,604,...,0.824,51,292,343,313,86,28,176,197,1791
5,201942,2014-15,00,1610612761,TOR,25.0,60,60,2100.0,409,...,0.832,41,236,277,210,73,11,137,122,1204
6,201942,2015-16,00,1610612761,TOR,26.0,78,78,2804.0,614,...,0.850,64,285,349,315,81,21,175,167,1830
7,201942,2016-17,00,1610612761,TOR,27.0,74,74,2620.0,721,...,0.842,70,316,386,290,78,13,180,134,2020
8,201942,2017-18,00,1610612761,TOR,28.0,80,80,2712.0,645,...,0.825,59,256,315,417,85,22,175,151,1840
9,201942,2018-19,00,1610612759,SAS,29.0,77,77,2688.0,631,...,0.830,54,408,462,475,86,36,199,177,1635
10,201942,2019-20,00,1610612759,SAS,30.0,68,68,2316.0,557,...,0.845,44,331,375,380,70,20,164,180,1504
11,201942,2020-21,00,1610612759,SAS,31.0,61,61,2056.0,455,...,0.880,40,219,259,422,56,15,119,128,1316
12,201942,2021-22,00,1610612741,CHI,32.0,76,76,2743.0,774,...,0.877,56,336,392,374,68,24,181,178,2118
13,201942,2022-23,00,1610612741,CHI,33.0,55,55,1988.0,503,...,0.881,23,230,253,280,54,29,121,147,1390

In [ ]:

#Donovan Mitchell
career = playercareerstats.PlayerCareerStats(player_id='1628378')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1628378,2017-18,00,1610612762,UTA,21.0,79,71,2638.0,595,...,0.805,52,244,296,291,118,27,215,213,1616
1,1628378,2018-19,00,1610612762,UTA,22.0,77,77,2598.0,661,...,0.806,59,257,316,322,106,31,218,208,1829
2,1628378,2019-20,00,1610612762,UTA,23.0,69,69,2364.0,602,...,0.863,53,251,304,294,70,14,184,172,1655
3,1628378,2020-21,00,1610612762,UTA,24.0,53,53,1771.0,478,...,0.845,50,185,235,277,52,15,147,117,1401
4,1628378,2021-22,00,1610612762,UTA,25.0,67,67,2266.0,617,...,0.853,55,227,282,358,99,12,200,164,1733
5,1628378,2022-23,00,1610612739,CLE,26.0,53,53,1875.0,503,...,0.876,49,164,213,253,82,21,143,127,1441

In [ ]:

#Luka Doncic
career = playercareerstats.PlayerCareerStats(player_id='1629029')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1629029,2018-19,00,1610612742,DAL,20.0,72,72,2318.0,506,...,0.713,86,477,563,429,77,25,247,137,1526
1,1629029,2019-20,00,1610612742,DAL,21.0,61,61,2047.0,581,...,0.758,78,495,573,538,62,14,260,153,1759
2,1629029,2020-21,00,1610612742,DAL,22.0,66,66,2262.0,647,...,0.730,54,473,527,567,64,36,281,152,1830
3,1629029,2021-22,00,1610612742,DAL,23.0,65,65,2301.0,641,...,0.744,56,537,593,568,75,36,292,145,1847
4,1629029,2022-23,00,1610612742,DAL,23.0,52,52,1892.0,580,...,0.732,45,412,457,422,79,26,190,137,1720

In [ ]:

#Cory Joseph
career = playercareerstats.PlayerCareerStats(player_id='202709')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,202709,2011-12,00,1610612759,SAS,20.0,29,1,266.0,22,...,0.647,5,20,25,34,7,3,12,16,58
1,202709,2012-13,00,1610612759,SAS,21.0,28,9,388.0,51,...,0.857,12,40,52,53,15,4,21,25,126
2,202709,2013-14,00,1610612759,SAS,22.0,68,19,936.0,126,...,0.823,32,75,107,114,35,14,43,84,343
3,202709,2014-15,00,1610612759,SAS,23.0,79,14,1444.0,207,...,0.734,44,148,192,188,46,17,67,105,535
4,202709,2015-16,00,1610612761,TOR,24.0,80,4,2046.0,257,...,0.764,39,171,210,250,63,20,102,131,677
5,202709,2016-17,00,1610612761,TOR,25.0,80,22,2003.0,299,...,0.770,51,184,235,265,66,13,108,140,740
6,202709,2017-18,00,1610612754,IND,26.0,82,17,2210.0,256,...,0.745,39,224,263,260,80,18,87,141,649
7,202709,2018-19,00,1610612754,IND,27.0,82,9,2063.0,226,...,0.698,39,240,279,321,94,22,80,131,537
8,202709,2019-20,00,1610612758,SAC,28.0,72,26,1759.0,171,...,0.857,44,144,188,251,53,21,80,133,458
9,202709,2020-21,00,1610612758,SAC,29.0,44,2,944.0,111,...,0.766,25,74,99,108,39,9,44,98,289
10,202709,2020-21,00,1610612765,DET,29.0,19,11,502.0,89,...,0.878,10,50,60,105,22,9,35,41,228
11,202709,2020-21,00,0,TOT,29.0,63,13,1446.0,200,...,0.818,35,124,159,213,61,18,79,139,517
12,202709,2021-22,00,1610612765,DET,30.0,65,39,1600.0,178,...,0.885,29,145,174,237,42,17,85,147,521
13,202709,2022-23,00,1610612765,DET,31.0,43,2,686.0,73,...,0.769,10,46,56,137,19,6,32,64,203

In [ ]:

#Frank Kaminsky
career = playercareerstats.PlayerCareerStats(player_id='1626163')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1626163,2015-16,00,1610612766,CHA,23.0,81,3,1708.0,215,...,0.730,69,266,335,98,38,43,58,126,606
1,1626163,2016-17,00,1610612766,CHA,24.0,75,16,1954.0,320,...,0.756,57,279,336,162,46,34,76,139,874
2,1626163,2017-18,00,1610612766,CHA,25.0,79,4,1835.0,307,...,0.799,46,242,288,129,36,19,66,95,873
3,1626163,2018-19,00,1610612766,CHA,26.0,47,0,755.0,138,...,0.738,39,124,163,63,12,12,41,68,405
4,1626163,2019-20,00,1610612756,PHX,27.0,39,13,777.0,138,...,0.678,35,141,176,75,14,10,37,75,378
5,1626163,2020-21,00,1610612756,PHX,28.0,47,13,715.0,121,...,0.617,36,152,188,79,14,17,22,70,310
6,1626163,2021-22,00,1610612756,PHX,29.0,9,0,181.0,36,...,0.900,11,30,41,13,8,7,5,14,95
7,1626163,2022-23,00,1610612737,ATL,29.0,26,0,176.0,25,...,0.833,3,33,36,21,5,1,9,21,71
8,1626163,2022-23,00,1610612745,HOU,29.0,3,0,24.0,1,...,1.000,1,3,4,6,1,2,0,1,6
9,1626163,2022-23,00,0,TOT,29.0,29,0,200.0,26,...,0.875,4,36,40,27,6,3,9,22,77

In [ ]:

#Buddy Heild
career = playercareerstats.PlayerCareerStats(player_id='1627741')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1627741,2016-17,00,1610612740,NOP,24.0,57,37,1161.0,185,...,0.879,19,147,166,77,18,7,48,81,488
1,1627741,2016-17,00,1610612758,SAC,24.0,25,18,727.0,142,...,0.814,16,87,103,44,20,2,53,34,378
2,1627741,2016-17,00,0,TOT,24.0,82,55,1888.0,327,...,0.842,35,234,269,121,38,9,101,115,866
3,1627741,2017-18,00,1610612758,SAC,25.0,80,13,2024.0,416,...,0.877,55,252,307,155,85,22,124,148,1079
4,1627741,2018-19,00,1610612758,SAC,26.0,82,82,2615.0,623,...,0.886,106,306,412,205,58,33,146,202,1695
5,1627741,2019-20,00,1610612758,SAC,27.0,72,44,2216.0,498,...,0.846,57,271,328,213,66,17,168,165,1382
6,1627741,2020-21,00,1610612758,SAC,28.0,71,71,2433.0,403,...,0.846,29,305,334,257,63,30,130,175,1176
7,1627741,2021-22,00,1610612758,SAC,29.0,55,6,1574.0,265,...,0.870,43,178,221,105,48,15,90,113,792
8,1627741,2021-22,00,1610612754,IND,29.0,26,26,925.0,181,...,0.886,23,109,132,124,25,10,63,71,473
9,1627741,2021-22,00,0,TOT,29.0,81,32,2499.0,446,...,0.874,66,287,353,229,73,25,153,184,1265
10,1627741,2022-23,00,1610612754,IND,30.0,62,62,1989.0,381,...,0.860,52,252,304,167,72,19,114,124,1079

In [ ]:

#Tyus Jones
career = playercareerstats.PlayerCareerStats(player_id='1626145')
career.get_data_frames()[0]

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

In [ ]:

#Jimmy Butler
career = playercareerstats.PlayerCareerStats(player_id='202710')
career.get_data_frames()[0]

In [ ]:

#Giannis Antetokounmpo
career = playercareerstats.PlayerCareerStats(player_id='203507')
career.get_data_frames()[0]

In [ ]:

#Kyle Anderson
career = playercareerstats.PlayerCareerStats(player_id='203937')
career.get_data_frames()[0]

In [ ]:

#Brandon Ingram
career = playercareerstats.PlayerCareerStats(player_id='1627742')
career.get_data_frames()[0]

In [ ]:

#Julius Randle
career = playercareerstats.PlayerCareerStats(player_id='203944')
career.get_data_frames()[0]

In [ ]:

#Shai Gilgeous-Alexander
career = playercareerstats.PlayerCareerStats(player_id='1628983')
career.get_data_frames()[0]

In [ ]:

#Wendell Carter Jr
career = playercareerstats.PlayerCareerStats(player_id='1628976')
career.get_data_frames()[0]

In [ ]:

#Joel Embiid
career = playercareerstats.PlayerCareerStats(player_id='203954')
career.get_data_frames()[0]

In [ ]:

#Devin Booker
career = playercareerstats.PlayerCareerStats(player_id='1626164')
career.get_data_frames()[0]

In [ ]:

#Damian Lillard
career = playercareerstats.PlayerCareerStats(player_id='203081')
career.get_data_frames()[0]

In [ ]:

#Domantas Sabonis
career = playercareerstats.PlayerCareerStats(player_id='1627734')
career.get_data_frames()[0]

In [ ]:

#Devonte' Graham
career = playercareerstats.PlayerCareerStats(player_id='1628984')
career.get_data_frames()[0]

In [ ]:

#Pascal Siakam
career = playercareerstats.PlayerCareerStats(player_id='1627783')
career.get_data_frames()[0]

In [ ]:

#Collin Sexton
career = playercareerstats.PlayerCareerStats(player_id='1629012')
career.get_data_frames()[0]

In [ ]:

#Bradley Beal
career = playercareerstats.PlayerCareerStats(player_id='203078')
career.get_data_frames()[0]

In [ ]:
df = career.get_data_frames()[0]
plt.figure(figsize = (6,4), dpi=200)
sns.scatterplot(x = 'PTS', y = 'GP', data = df)

In [ ]:

#Lebron James
career = playercareerstats.PlayerCareerStats(player_id='2544')
career.get_data_frames()[0]

In [ ]:
df = career.get_data_frames()[0]
plt.figure(figsize = (6,4), dpi=200)
sns.scatterplot(x = 'PTS', y = 'GP', data = df)

In [ ]:

#Stephen Curry
career = playercareerstats.PlayerCareerStats(player_id='201939')
career.get_data_frames()[0]

In [ ]:
df = career.get_data_frames()[0]
plt.figure(figsize = (6,4), dpi=200)
sns.scatterplot(x = 'PTS', y = 'GP', data = df)

In [ ]:
plt.figure(figsize=(10,4),dpi=200)
sns.countplot(x='PTS',data=df,hue='PLAYER_ID')

In [ ]:


# Retrieve career statistics for Stephen Curry
curry_career = playercareerstats.PlayerCareerStats(player_id='201939')
curry_df = curry_career.get_data_frames()[0]

# Retrieve career statistics for LeBron James
james_career = playercareerstats.PlayerCareerStats(player_id='2544')
james_df = james_career.get_data_frames()[0]

In [ ]:
plt.figure(figsize=(10,4),dpi=200)
sns.countplot(x='PTS',data=df,hue='PLAYER_ID')

In [ ]:

career = playercareerstats.PlayerCareerStats()
career.get_data_frames()[0]

In [ ]:
df = career.get_data_frames()[0]

In [ ]:
df.head()

In [ ]:


# Stephen Curry
curry_career = playercareerstats.PlayerCareerStats(player_id='201939')
curry_stats = curry_career.get_data_frames()[0]

# LeBron James
james_career = playercareerstats.PlayerCareerStats(player_id='2544')
james_stats = james_career.get_data_frames()[0]

In [ ]:

#Stephen Curry
career = playercareerstats.PlayerCareerStats(player_id='201939')
career.get_data_frames()[0]

#Lebron James
career = playercareerstats.PlayerCareerStats(player_id='2544')
career.get_data_frames()[0]

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt


# Get career points for Stephen Curry
curry_career = playercareerstats.PlayerCareerStats(player_id='201939')
curry_points = pd.DataFrame(curry_career.get_data_frames()[0][['SEASON_ID', 'PTS']])

# Get career points for LeBron James
james_career = playercareerstats.PlayerCareerStats(player_id='2544')
james_points = pd.DataFrame(james_career.get_data_frames()[0][['SEASON_ID', 'PTS']])

# Merge data for both players
merged_points = pd.merge(curry_points, james_points, on='SEASON_ID', suffixes=('_Curry', '_James'))

# Create bar plot
fig, ax = plt.subplots()
merged_points.plot(kind='barh', x='SEASON_ID', ax=ax)
ax.set_xlabel('Points')
ax.set_ylabel('Season')
ax.set_title('Career Points Comparison: Stephen Curry vs. LeBron James')
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt


# Get career points for Stephen Curry
curry_career = playercareerstats.PlayerCareerStats(player_id='201939')
curry_points = pd.DataFrame(curry_career.get_data_frames()[0][['SEASON_ID', 'PTS']])

# Get career points for LeBron James
james_career = playercareerstats.PlayerCareerStats(player_id='2544')
james_points = pd.DataFrame(james_career.get_data_frames()[0][['SEASON_ID', 'PTS']])

# Merge data for both players
merged_points = pd.merge(curry_points, james_points, on='SEASON_ID', suffixes=('_Curry', '_James'))

# Create vertical bar plot
fig, ax = plt.subplots()
merged_points.plot(kind='bar', x='SEASON_ID', ax=ax)
ax.set_xlabel('Season')
ax.set_ylabel('Points')
ax.set_title('Career Points Comparison: Stephen Curry vs. LeBron James')
plt.show()